# TODO: Before submission - Update GitHub URLs! See ../.github/NAME_CHANGE_CHECKLIST.md
blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/fidpa/hablara/security/advisories/new
    about: Report security issues privately through GitHub Security Advisories
  - name: Question or Discussion
    url: https://github.com/fidpa/hablara/discussions
    about: Ask questions or discuss ideas with the community
